name: freshfield_sdk
description: A Freshfield changelog management SDK for your Flutter app.
version: 0.1.0
homepage: https://github.com/freshfieldio/freshfield_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
